# Generated by Django 5.0.7 on 2024-07-27 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrendador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Arrendatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idContrato', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(max_length=100)),
                ('inicio_contrato', models.DateTimeField()),
                ('fin_contrato', models.DateField()),
                ('costo_alquiler', models.IntegerField()),
                ('arrendador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.arrendador')),
                ('arrendatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.arrendatario')),
            ],
        ),
        migrations.AddField(
            model_name='arrendador',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.persona'),
        ),
    ]
