# Generated by Django 5.0.7 on 2024-07-28 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrendador',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='arrendatario',
            name='identificacion',
        ),
        migrations.AddField(
            model_name='arrendador',
            name='id_arrendador',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='arrendador',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventario.arrendador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='id_arrendatario',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arrendatario',
            name='persona',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inventario.persona'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='persona',
            name='ci',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
